apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: semver
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: HOME
                value: /tekton/home
            name: ""
            resources:
              # override limits for all containers here
              limits: {}
            workingDir: /workspace/source
          steps:
            - script: |
                #!/usr/bin/env sh
                last_message="$(git log --no-merges -1 --pretty=%B)"
                echo "Last commit message is: $last_message."
                (
                case $last_message in
                  "fix:"*) echo "Contains SemVer release info" && exit 0 ;;
                  "feat:"*) echo "Contains SemVer release info" && exit 0 ;;
                  "BREAKING CHANGE:"*) echo "Contains SemVer release info" && exit 0 ;;
                  *)  echo "Missing SemVer release info" && exit 1  ;;
                esac
                )
              image: alpine/git
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
              name: semver-check
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
