apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: HOME
                value: /tekton/home
            name: ""
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
            workingDir: /workspace/source
          steps:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1
              name: build-dotnet-restore
              resources: {}
              script: |
                #!/bin/bash
                dotnet restore
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
